name: QR Code Test

on:
  push:
  workflow_dispatch:

jobs:
  test-qr:
    runs-on: ubuntu-latest

    steps:
      - name: Test QR Code Formatting
        run: |
          # Test URL
          TEST_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts"
          
          # Install qrencode
          sudo apt-get update && sudo apt-get install -y qrencode
          
          echo "🧪 Testing different QR code formats:"
          echo ""
          
          echo "1️⃣ Standard format:"
          qrencode -t utf8 "$TEST_URL"
          echo ""
          
          echo "2️⃣ No margins:"
          qrencode -t utf8 -m 0 "$TEST_URL"
          echo ""
          
          echo "3️⃣ Small blocks:"
          qrencode -t utf8 -m 0 -s 1 "$TEST_URL"
          echo ""
          
          echo "4️⃣ Doubled blocks:"
          qrencode -t utf8 -m 0 -s 1 "$TEST_URL" | sed 's/█/██/g'
          echo ""
          
          echo "5️⃣ ASCII format:"
          qrencode -t ansiutf8 -m 0 "$TEST_URL"
          echo ""
          
          echo "🔗 Test URL: $TEST_URL"